# Travis Configuration for QuantEcon.py
#
# Thank you for the writeup given by dan-blanchard at https://gist.github.com/dan-blanchard/7045057
#

sudo: false        #Use new Container Infrastructure
language: python

cache:
  pip: true
  directories:
    # osx-specific caches
    - $HOME/Library/Caches/pip

addons:
  apt:
    packages:
      - hdf5-tools
  homebrew:
    packages:
      - hdf5

matrix:
  include:
    - python: 3.6
    - os: osx
      osx_image: xcode10
      sudo: required
      env: TRAVIS_PYTHON_VERSION=3.7
      language: generic
      before_install:
      - pip install virtualenv
      - virtualenv env -p python3
      - source env/bin/activate

notifications:
  email: false

branches:
  only:
    - master

install:
  - pip install -U pip nose coveralls coverage numpy scipy pandas numba sympy ipython statsmodels
  - pip install tables
  - python setup.py install

script:
  - nosetests --with-coverage -a "!slow" --cover-package=quantecon

after_success:
  - coveralls
  # Enable this to occasionally test performance
  # - nosetests -a "slow"
